SHA2017-badge/Firmware

- .travis.yml
- Makefile
- README.md
I was never a big fan of the Make magic compared to a simple `source set_env.sh`
> Attempt to stabalize build (fixes #13)

- .gitignore
- components/badge/badge_mpr121.c
- components/badge/badge_pins.h
- components/badge/badge_power.c
- components/badge/badge_power.h
- main/demo_power.c
- main/demo_power.h
- main/main.c
- set_env.sh
Add support for reading Vusb/Vbat voltage and charging status.
> Basvs charging status

- .gitmodules
- components/badge/badge_button.h
- components/badge/badge_input.h
- components/ugfx/gfxconf.h
- components/ugfx/ginput_lld_toggle.c
- components/ugfx/ginput_lld_toggle_config.h
- main/demo_ugfx.c
Nice teamwork here :).
ugfx touch input only tested with 'old' badge. demo_ugfx should output
some logging immediately whenever a key state changes, and every 5 seconds
report the state of the 'up' key. Hooking up toggles to GEvents not yet tried.
> ugfx touch input (and some more goodies)

- main/demo_ugfx.c
use 'up' to scroll through screens in the ugfx demo. I expected 'listeners' to
be a bit more dynamic though :/
> Demo listening for keypresses through GEVENT

- .gitmodules
- .travis.yml
- CHANGELOG.md
- README.md
Travis jobs now running on our container-based trusty beta. 
https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta
> Travis build emulator, README updated on emulator compilation

- README.md
> Updated micropython to latest upstream (ahead of micropython-esp32)

- .travis.yml
- README.md
We need those Ephemeral Diffie-Hellman's
> Emulator on mbedtls instead of axtls

- .travis.yml
- README.md
On Ubuntu Xenial and up there is a lib that seems to work available . . 
https://launchpad.net/ubuntu/+source/mbedtls
> Only have travis be a bad boy and use local mbedtls

- components/ugfx/board_framebuffer.h
Latest examples, micropython and moved taget_lut to variable to enable changing of LUT
> Sneaking in some updates

- components/badge/badge_eink.c
also do sw-reset on GDEH-display init.
> remove all busy_wait calls. it's now automatically done on next command.

- components/ugfx/gfxconf.h
> Enabled PNG/BMP support and romFS in gfxconf

- components/badge/Kconfig
- components/badge/badge.c
- components/badge/badge.h
- components/badge/badge_mpr121.c
- components/badge/badge_mpr121.h
Misc changes:
- improve doxygen documentation
- improve types in badge_mpr121.h
- add badge_mpr121_get_touch_info() to replace
badge_mpr121_get_electrode_data()
> Add hardcoded touch baselines; misc small changes.

- components/badge/badge_leds.h
- components/badge/badge_mpr121.h
- components/badge/badge_vibrator.c
- components/badge/badge_vibrator.h
- main/demo_leds.c
- main/demo_mpr121.c
- added more doxygen comments
- added deprecated-attribute to deprecated methods
- fix demo-code to not use the deprecated methods
- fix badge_vibrator_activate() to use an unsigned integer
> Misc improvements

- Makefile
- components/badge/Kconfig
- components/badge/badge_power.c
- components/graph/component.mk
- components/sha2017/component.mk
- components/ugfx/component.mk
- main/component.mk
Added debug-messages to debug issue #83 
Kartoffel did some testing. Test-results showed that the actual voltages were 10% lower than the voltages we were returning.
> Add badge_power debugging; add 0.9 factor to voltage reads

- components/png/deflate_reader.c
- components/png/mem_reader.c
- components/png/mem_reader.h
- components/png/png_reader.c
- png parser fixes and optimizations
- add mem-reader object
> PNG updates

- components/badge/badge_pins.h
- components/badge/badge_power.c
All leds and sdcard pins are now configured as input when disabling power.
Added sdcard pin-numbers for the old rev 0.0.2 badge.
> fix issue #83.

- components/badge/badge.c
- components/badge/badge_mpr121.c
- components/badge/badge_mpr121.h
- components/badge/badge_nvs.c
- components/badge/badge_nvs.h
- firmware/main/Kconfig.projbuild
- firmware/main/main.c
(and add dependency on badge_i2c in badge_mpr121)
> test-firmware work-in-progress..

- components/badge/badge.c
- components/badge/badge_base.c
- components/badge/badge_eink.c
- components/badge/badge_eink_dev.c
- components/badge/badge_eink_lut.c
- components/badge/badge_gpiobutton.c
- components/badge/badge_i2c.c
- components/badge/badge_input.c
- components/badge/badge_leds.c
- components/badge/badge_mpr121.c
- components/badge/badge_nvs.c
- components/badge/badge_portexp.c
- components/badge/badge_power.c
- components/badge/badge_sdcard.c
- components/badge/badge_touch.c
- components/badge/badge_vibrator.c
> Basvs bughunt

- components/bpp-if/Kconfig
- components/bpp-if/bpp_sniffer.c
This also "fixes" the bootloop issue I was having on micropython by pinning the two tasks to cpu 0 instead of 1
> Configurable BPP

- components/badge/badge_leds.c
> ignore spi-bus-initialize errors.

- .travis.yml
Adding -j3 flag to utilize both cores..
Should halve travis time
> Multi core travis compilation

- components/png/crc32.c
(this saves 1 KB lookup-table)
> use the crc32 implementation from the crc32 rom.

- .gitmodules
- .travis.yml
- set_env.sh
> updated xtensa toolchain

- components/badge/badge.c
- components/badge/badge_mpr121.c
- components/badge/badge_mpr121.h
> better handling of early key-presses.

- components/badge-first-run/badge_first_run.c
If it says we are charging, then the battery should have more than 0.1 V.
Message can be ignored by pressing button A.
> Add test for charging pin.

- components/ugfx-glue/gfx_userfs.c
- components/ugfx-glue/gfx_userfs.h
- components/ugfx-glue/gfxconf.h
With this patch UGFX can finally see the regular filesystem.
Also requires https://github.com/SHA2017-badge/micropython-esp32/pull/130
> Added bindings to ESP-IDF native filesystem library for ugfx via USERFS

- components/png/png_reader.c
- components/png/png_reader.h
We can now get the width and height from an image before decoding it
> split png header and data parser.

- components/badge/badge_eink.c
This is a behaviour change!! Should be tested!! (but I think it's the right thing to do..)
> BADGE_EINK_LUT_FULL shouldn't do a partial update.

- main/demo_greyscale2.c
- main/demo_partial_update.c
> remove unused variables.

- components/badge-first-run/badge_first_run.c
- components/badge/badge_eink.c
- components/badge/badge_eink.h
- components/ugfx-glue/board_framebuffer.h
- main/demo_greyscale_img4.c
- main/demo_sdcard_image.c
- added BADGE_EINK_MAX_LAYERS constant
- declared display flags as enum badge_eink_flags_t
- updated doxygen documentation
> misc minor updates. no changes in compiled code.

- components/bpp-if/bpp_init.c
- components/bpp-if/bpp_init.h
- components/bpp-recv/powerdown.c
- components/bpp-recv/powerdown.h
Should make it work nicely with BPP.
> Let micropython use the bpp powerdown manager

- components/badge-first-run/badge_first_run.c
https://github.com/SHA2017-badge/Firmware/issues/203
> Increase Vusb max from 5.5 to 5.7 volt.

- components/sha2017/sha2017_ota.c
> Rewrite OTA update code

- components/badge/badge_eink_dev.c
- components/badge/badge_eink_dev.h
Ref: https://github.com/SHA2017-badge/Firmware/pull/214
> Switched to spi driver API defined in the esp-idf instead of using direct setting of configuration registers
