SHA2017-badge/Firmware

main/demo_power.c

The rev0.0.1 board doesn't have vbat_sense, vusb_sense. Use #defines to work around it.

Bugfix: add #defines to demo_power.c

---

components/badge/badge.c
components/badge/badge_button.c
components/badge/badge_button.h
components/badge/badge_input.c
components/badge/badge_input.h
components/ugfx/ginput_lld_toggle.c
components/ugfx/ginput_lld_toggle_config.h

- add badge_input_notify-hook to hardware-abstraction-framework
- use badge_input_add_event() to add button-presses to the queue
(and call notify hook if set)
- remove gpio and touch handling from ugfx framework

splitting high-level ugfx driver from low-level input drivers

---

components/badge/Kconfig
components/badge/badge.c
components/badge/badge_button.c
components/badge/badge_eink_dev.c
components/badge/badge_input.c
components/badge/badge_mpr121.c
components/badge/badge_mpr121.h
components/badge/badge_portexp.c
components/badge/badge_touch.c

- add config options for input and eink debug
- add button-release handling
- prefix every printf message with its driver name
e.g. 'badge_mpr121: i2c read reg(0x%02x): 0x%02x\n'
- mpr121: improve interrupt handling
- better error-handling
- better handling of multi-button presses
- handling of over-current situation
- mpr121: read gpio-level from status register, not from data-register.

Fixes in low-level drivers

---

components/badge/badge_button.h
components/badge/badge_input.h

In order to make the button interface reusable on unix, it will be nicer to have these defines in a header that doesn't bring along other dependencies.

Moved button definitions to a header that doesn't depend on FreeRTOS queues

---

components/badge/Kconfig
components/badge/badge_leds.c
components/badge/badge_leds.h
components/badge/badge_pins.h

- add badge_leds_enable() to enable power to the leds bar.
- add badge_leds_disable() to disable power to the leds bar.
- add badge_leds_send_data(data, len) to send a data-stream to the leds-bar.
(with arbitrary length to support external leds-bar)
- move the WS2812 / SK6812 selection from badge_pins.h to the config-menu.
WS2812 is now a hack on the data-stream sent with badge_leds_send_data()

rewrite badge_leds driver a bit;

---

components/badge/Kconfig
components/badge/badge_eink.c
components/badge/badge_eink.h
components/badge/badge_eink_lut.c
components/badge/badge_eink_lut.h
components/ugfx/board_framebuffer.h
main/demo_dot1.c
main/demo_greyscale2.c
main/demo_greyscale_img1.c
main/demo_greyscale_img2.c
main/demo_greyscale_img3.c
main/demo_mpr121.c
main/demo_power.c
main/demo_test_adc.c
main/demo_text1.c
main/demo_text2.c
main/main.c

- added partial updates for the depg (write old image to RAM2
with command 0x26)
- luts are now generated. can now use the same input for both
display types.
- altered badge_eink_update struct a bit:
- added lut_flags. bitmapped options:
- LUT_FLAG_FIRST (no old image available)
- LUT_FLAG_PARTIAL (remove all non-partial elements)
- LUT_FLAG_WHITE (only make pixels whiter)
- LUT_FLAG_BLACK (only make pixels blacker)
- changed type of lut_custom; it's now in the more generic format.
- added flag DISPLAY_FLAG_FULL_UPDATE, which disables the
automatic partial update
- added DISPLAY_FLAG_LUT(lut) helper
- removed the fading effect from the menu. it caused too much ghosting.
- improved type definitions and doxygen documentation.

Improve eink-display; add partial-updates to depg driver

---

components/badge/badge_leds.c
components/badge/badge_power.c
components/badge/badge_power.h
main/demo_leds.c

- moved power-handling to badge_power.
- now initializes the SPI every time we enable the leds-bar.
(and de-initializes the SPI every time we disable the leds-bar)
- we're using the gpio driver to ignore the impedance level of the
pin.
- added call to badge_power_init(); added done flag.
(leds demo)
-  actual ordering of the 'rgbw' colors is 'grbw'.

Fix issue #59; initialize SPI only on active use

---

components/badge/badge.c
components/badge/badge_base.c
components/badge/badge_base.h
components/badge/badge_eink.c
components/badge/badge_eink_dev.c
components/badge/badge_gpiobutton.c
components/badge/badge_i2c.c
components/badge/badge_input.c
components/badge/badge_mpr121.c
components/badge/badge_portexp.c
components/badge/badge_sdcard.c
components/badge/badge_touch.c
components/badge/badge_vibrator.c

Add boolean flag to every *_init() method to avoid double initialization.
(and initialize gpio_config_t io_conf as struct instead of per field)

Allow badge_*_init() to be called multiple times.

---

components/ugfx/gfxconf.h

We don't want to miss a draw before flushing, because it might be a long time
before we flush again.

Draw immediately

---

components/sha2017/sha2017_ota.c
components/sha2017/sha2017_ota_graphics.c
components/sha2017/sha2017_ota_graphics.h

(avoid flashing incompatible images)
- add 'rev0.0.1' and 'rev0.1.0' tag for older badges.
- add flash size. (compiled in from config; NOT auto-detected)
This does *not* mean that all possible combinations should be available on the server.
We probably only want to build firmware-16MB.bin, and maybe firmware-4MB.bin

Let remote filename depend on current config.

---

components/badge/badge_i2c.c
components/badge/badge_i2c.h
components/badge/badge_mpr121.c
components/badge/badge_mpr121.h
components/badge/badge_portexp.c

- update mpr121 driver to make use of this.
- remove deprecated badge_mpr121_get_electrode_data method.

Update badge-i2c code to support reading multiple values.

---

components/sha2017/sha2017_ota.c

ssid/password:
- use the ssid and password from nvs
(fixed: set the length of the buffer before requesting the string)
- when not set or empty, use the hardcoded ssid/password
get-configured-boot:
was only used to show the currently running partition. (which is not the same)

fix nvs ssid/password; remove the get-configured-boot.

---

components/badge/badge_eink.c
components/badge/badge_eink.h
components/ugfx/board_framebuffer.h

00:58 <@tsd> bas-ugfx branch now has a 8 bit greyscale backend for ugfx
00:58 <@tsd> ugfx demo in the c firmware still works
01:00 <@tsd> now you can load a png-image directly into ugfx's fbi->pixels
The switch between black and white is somewhere around greyscale value 0xb8.

use 8 bit greyscale backend buffer for ugfx

---

firmware/main/Kconfig.projbuild
firmware/main/main.c

- make waiting configurable (default: no waiting), but we need it for debugging.
- store the default ssid/password in nvs.

small first-run updates

---

components/badge/badge_eink_dev.c

return-type was changed in the big error-checking commit.

fix badge_eink_dev_reset() return type.

---

components/badge-first-run/badge_first_run.c

The battery connector is sometime a b*tch... Now you can leave the battery in :)

Make vbat on firstrun a warning

---

components/badge/badge_eink.c
components/badge/badge_eink_dev.h

tested and works here.
.. but it might not be a good idea to put it in today's release

move badge_eink_{tmp,old}buf to iram and save 9.2 KB of main memory.

---

components/badge/badge_nvs.c
components/badge/badge_nvs.h

also includes:
- code cleanup
- use readonly when reading strings
- better error-checking and cleanup

erase key before setting key.

---

components/badge/badge_leds.c
components/badge/badge_leds.h

Not to be confused with the micropython method 'badge.leds_set_state()', which is a wrapper around badge.leds_send_data()'.

remove deprecated unused method badge_leds_set_state()

---

components/badge-first-run/badge_first_run.c
components/badge/badge_eink_dev.c
components/badge/badge_eink_lut.c
components/badge/badge_gpiobutton.c
components/badge/badge_i2c.c
components/badge/badge_input.c
components/badge/badge_leds.c
components/badge/badge_mpr121.c
components/badge/badge_portexp.c
components/badge/badge_power.c
components/badge/badge_touch.c

The ESP_LOGx() methods are unfortunately not allowed in the
interrupt handlers. We still have to use the ets_printf() there.

use ESP_LOGx() where possible.

---

components/badge/badge_eink.c
components/badge/badge_eink_lut.c
components/badge/badge_eink_lut.h

cleanups 70 bytes of main memory; will make other pending patches
easier.

move eink lut data from static buffer to caller-stack

---

components/badge/badge_eink.c
components/badge/badge_eink.h

It wasn't used. There's no need for it.

Removing struct badge_eink_update eink_upd_default.

---

components/badge/badge_eink.c
components/badge/badge_eink.h
main/demo_dot1.c
main/demo_dot1.h
main/demo_greyscale1.c
main/demo_greyscale1.h
main/demo_greyscale2.c
main/demo_greyscale2.h
main/demo_greyscale_img1.c
main/demo_greyscale_img1.h
main/demo_greyscale_img2.c
main/demo_greyscale_img2.h
main/demo_greyscale_img3.c
main/demo_greyscale_img3.h
main/demo_partial_update.c
main/main.c

This makes the code a bit cleaner; we did already always write the
raw buffer to the eink just before the update.
Now all demo* code works on both displays.

Add raw screen buffer to badge_eink_update() call.

---

components/badge-first-run/badge_first_run.c
components/badge/Kconfig
components/badge/badge.c
components/badge/badge_eink.c
components/badge/badge_eink.h
components/badge/badge_eink_dev.c
components/badge/badge_eink_dev.h
components/badge/badge_eink_lut.c
components/badge/badge_eink_types.h
components/ugfx-glue/board_framebuffer.h

There was a request to support OTA updates on custom-built badges with the GDEH display.
With this patch and one nvs setting, we support this.

Support both eink types.

---

components/badge/badge_leds.c

With this patch, the leds enable and disable things work.
To test this:
badge.leds_send_data(b'\x01\x00\x00\x00', 4)
// green light should go on
badge.leds_disable()
// green light should go off
badge.eink_png(0, 0, '/media/hacking.png')
ugfx.flush()
// hacking image (black/white) should appear
badge.leds_send_data(b'\x01\x00\x00\x00', 4)
// green light should go on

workaround for the leds-disable.

---

components/badge/badge.h
components/badge/badge_base.h
components/badge/badge_cpt112s.h
components/badge/badge_eink.h
components/badge/badge_eink_dev.h
components/badge/badge_eink_fb.h
components/badge/badge_eink_lut.h
components/badge/badge_fxl6408.h
components/badge/badge_gpiobutton.h
components/badge/badge_i2c.h
components/badge/badge_input.h
components/badge/badge_mpr121.h
components/badge/badge_nvs.h
components/badge/badge_power.h
components/badge/badge_sdcard.h
components/badge/badge_vibrator.h

Wraps all of the headers with `__BEGIN_DECLS` and `__END_DECLS` so that C++ compilers like the Arduino framework can include the badge component headers.

Allow C++ compilers to include the badge headers.

---

components/badge-first-run/badge_first_run.c
components/badge/badge_eink.c
components/badge/badge_eink.h
components/ugfx-glue/board_framebuffer.h
main/demo_greyscale_img4.c
main/demo_sdcard_image.c

BADGE_EINK_GREYSCALE renamed to BADGE_EINK_8BITPIXEL.
(it was already used as 8-bit-pixel indicator)
moved the greyscale hack to badge_eink_display_greyscale. Added layers attribute to specify the number of layers to display.

Refactoring badge_eink greyscale implementation

---

components/badge/Kconfig
components/badge/badge_pins.h

https://usercontent.irccloud-cdn.com/file/i4AmPkEF/1502650536.JPG

Add support for the decapitated final badge.

---

components/badge/badge_eink_dev.c
components/badge/badge_input.c
components/badge/badge_power.c
main/demo_test_adc.c

- badge_eink_dev: unused variable gpio_state.
- badge_input: unused variable badge_input_button_name.
- badge_power/demo_test_adc: adc1_get_voltage() is deprecated;
switch to adc1_get_raw()

Fix compiler warnings.
